[package]
name = "freya"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freya = "0.1"
dioxus = { version = "0.4", features = ["macro", "hooks"] }
