[package]
name = "freya_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = { version = "0.1.8" }
dioxus = { version = "0.4", features = [
    "macro",
    "hooks",
], default-features = false }
