[workspace]
resolver = "2"
members = [
    # "azul",
    "dioxus",
    "druid",
    "egui",
    "freya",
    # "fui",
    "iced",
    "imgui",
    "leptos",
    "makepad",
    "rui",
    "slint",
    # "tauri",
]
