name: build-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

concurrency:
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.runner }} / ${{ matrix.framework }}
    runs-on: ${{ matrix.runner }}-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu, windows, macos]
        framework: [azul, dioxus, druid, freya, iced, makepad, slint, tauri]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux only)
        if: matrix.runner == 'ubuntu'
        run: |
          sudo apt update -y
          case "${{ matrix.framework }}" in
          "dioxus")
            sudo apt install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
            ;;
          "druid")
            sudo apt install -y pkg-config libgtk-3-dev
            ;;
          "makepad")
            sudo apt install -y libxcursor-dev libasound2-dev libpulse-dev
            ;;
          *)
            echo "${{ matrix.framework }} does not require any dependencies"
            ;;
          esac

      - name: Build example
        working-directory: examples/
        run: cargo build --release --bin ${{matrix.framework}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.runner }}_${{ matrix.framework }}_example
          path: |
            examples/target/release/${{ matrix.framework }}?
            !examples/target/release/*.d
